version: "3"

services:
  droid1:
    image: redroid/redroid:11.0.0-latest
    container_name: cr_env_1
    privileged: true
    ports:
      - "5555:5555"
    volumes:
      - ./data1:/data
    command:
      - androidboot.redroid_width=720
      - androidboot.redroid_height=1280
      - androidboot.redroid_gpu_mode=guest
      - androidboot.redroid_arm_bridge=true

  droid2:
    image: redroid/redroid:11.0.0-latest
    container_name: cr_env_2
    privileged: true
    ports:
      - "5556:5555"
    volumes:
      - ./data2:/data
    command:
      - androidboot.redroid_width=720
      - androidboot.redroid_height=1280
      - androidboot.redroid_gpu_mode=guest
      - androidboot.redroid_arm_bridge=true
